language: node_js
node_js:
  - stable
cache:
  directories:
    - node_modules
before_script:
  - npm prune && npm install
  - ./node_modules/gatsby-cli/cli.js clean && ./node_modules/gatsby-cli/cli.js build
deploy:
  - provider: firebase
    skip_cleanup: true
    token: $FIREBASE_TOKEN
    on:
      branch: main
