language: node_js
node_js:
  - stable
cache:
  directories:
    - node_modules
before_script:
  - npm install
  - gatsby build
deploy:
  - provider: firebase
    skip_cleanup: true
    token: $FIREBASE_TOKEN
    on:
      branch: main
