language: node_js
node_js:
  - stable
cache:
  directories:
    - "$HOME/.npm"
    - "$HOME/.rvm"
before_script:
  - npm link submodules/map-citations
  - gatsby clean && gatsby build
deploy:
  - provider: firebase
    skip_cleanup: true
    token: $FIREBASE_TOKEN
    on:
      branch: main
