language: node_js
node_js:
  - stable
branches:
  only:
    - main
cache:
  directories:
    - node_modules
before_script:
  - npm install
  - gatsby build
deploy:
  provider: firebase
  token: $FIREBASE_TOKEN
